channels:
  - conda-forge

dependencies:
  - python=3.9.21
  # https://www.anaconda.com/utilizing-the-new-compilers-in-anaconda-distribution-5/
  - c-compiler=1.3.0
  - cmake=3.21.3
  - qt=5.15.8  # conda-forge does not have 5.13.2 available